Session.setDefault("activeView", GroupActions[0].name);
Session.setDefault("activeGame", null);
Session.setDefault("isGameActive", false)
Session.setDefault("gamePersonIndex", 0);
Session.setDefault("showGroup", null);
Session.setDefault("route", "home");
Session.setDefault("dropInArea", null);
Session.setDefault("showLoginModal", false);
Session.setDefault("showRegisterModal", false);